//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PocketDM.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DESCRIPTION                 102
#define IDR_MAINFRAME                   128
#define IDR_GDMFILE                     129
#define IDR_DMJOURTYPE                  129
#define IDD_DREAMEDIT                   130
#define IDR_DMLIST                      131
#define IDD_TESTDLG                     132
#define IDD_DREAMEDIT2                  133
#define IDD_DREAM                       136
#define IDD_DREAMBAR                    138
#define IDR_DREAMTOOLBAR                141
#define IDR_DREAMTOOLBAR2               142
#define IDD_PLACELIST                   145
#define IDI_ADD                         149
#define IDI_DEL                         150
#define IDI_NEW                         151
#define IDD_PLACEEDIT                   152
#define IDR_PLACETOOLBAR                157
#define IDI_OTHERTYPES                  160
#define IDI_LUCID                       161
#define IDI_CONSCIOUS                   162
#define IDI_ACTION                      163
#define IDI_SPEAK                       164
#define IDI_LOOP                        165
#define IDR_DREAM                       168
#define IDR_MAPTOOLBAR                  171
#define IDR_MAP                         173
#define IDR_MAPTOOLBAR256               174
#define IDR_MAINFRAME256                175
#define IDR_DEFAULTFILE                 185
#define IDR_DREAMBAR                    186
#define IDR_DREAMBAR256                 188
#define IDB_DREAMBAR256D                189
#define IDB_DREAMBAR256A                212
#define IDD_LAYERBAR                    213
#define IDR_DREAMBAR_SM                 215
#define IDB_DREAMBARD_SM                216
#define IDR_MAINFRAME_SM                217
#define IDR_MAPTOOLBAR_SM               218
#define IDD_PLACELIST2                  220
#define IDC_COMMENT                     1002
#define IDC_DESCRIPTION                 1003
#define IDC_DATE                        1005
#define IDC_TITLE                       1007
#define IDC_TYPE                        1008
#define IDC_CANCEL                      1009
#define IDC_APPLY                       1010
#define IDC_NEW                         1011
#define IDC_TAB                         1012
#define IDC_EDIT1                       1013
#define IDC_FIO                         1014
#define IDC_CAPT                        1016
#define IDC_SAVE                        1018
#define IDC_FIRST                       1021
#define IDC_PREV                        1022
#define IDC_NEXT                        1023
#define IDC_LAST                        1024
#define IDC_LIST                        1027
#define IDC_ADD                         1028
#define IDC_DELETE                      1029
#define IDC_GLOBALLIST                  1030
#define IDC_COLOR                       1032
#define IDC_TITLETEXT                   1033
#define IDC_DREAMJOURNAL                1035
#define IDC_DREAMMAP                    1036
#define IDC_COMBO1                      1038
#define IDC_BUILD_NUM                   1039
#define IDC_BUILDDATE                   1040
#define ID_MENUITEM32771                32771
#define IDM_DELETE                      32772
#define IDS_CAP_MENUITEM32772           32772
#define ID_BUTTONSAVE                   32773
#define ID_BUTTONCANCEL                 32774
#define ID_BUTTONNEW                    32775
#define ID_BUTTONFIRST                  32776
#define ID_BUTTONPREV                   32777
#define ID_BUTTONNEXT                   32778
#define ID_BUTTONLAST                   32779
#define ID_BUTTONDELETE                 32780
#define IDM_NEW                         32781
#define IDM_DVIEW                       32782
#define ID_BUTTON32783                  32783
#define ID_VIEW_DREAMBAR                32791
#define IDM_ZOOMIN                      32793
#define ID_ZOOMOUT                      32794
#define IDM_ZOOMOUT                     32794
#define IDM_MOVEPLACE                   32797
#define IDM_VIEWPLACE                   32798
#define IDM_DELETEPLACE                 32799
#define IDM_TAB                         32802
#define IDM_BIGICONS                    32804
#define IDM_SAVEXML                     32805
#define IDM_SETZONE                     32806
#define IDM_NEWZONE                     32807
#define IDM_DELZONE                     32808
#define IDM_ZONEEDITR                   32809
#define IDW_DIALOGBAR                   0xE804
#define IDW_MAPBAR                      0xE805
#define IDW_DREAMBAR                    0xE806
#define IDW_LAYERBAR                    0xE807
#define IDS_ERROR0                      61204
#define IDS_ERROR1                      61205
#define IDS_QUESTION1                   61206
#define IDS_DESCRIPTION                 61207
#define IDS_DATE                        61208
#define IDS_TITLE                       61209
#define IDS_DREAMEDIT                   61210
#define IDS_COMMENT                     61211
#define IDS_DREAM                       61212
#define IDS_QUESTION2                   61213
#define IDS_QUESTION3                   61214
#define IDS_PLACES                      61215
#define IDS_PLACE                       61216
#define IDS_PLACEEDIT                   61217
#define IDS_DREAMJOURNAL                61218
#define IDS_DELIRIOUS_LOOP              61219
#define IDS_DREAMMAP                    61219
#define IDS_SPEACH                      61220
#define IDS_COMPRESSEDFILE              61220
#define IDS_ACTION                      61221
#define IDS_XMLFILE                     61221
#define IDS_LUCID                       61222
#define IDS_ZONE                        61222
#define IDS_CONSCIOUS                   61223
#define IDS_ZONELIST                    61223
#define IDS_ZONES                       61224
#define IDS_ZONEEDIT                    61225

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        221
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
